r"""Convert a baseline run directory into LaTeX snippets and figures.

Reads ``runs/<timestamp>/summary.json`` plus the per-method CSVs produced by
``run_baselines.py`` and writes:

  * ``current works in progress/figures/auto/baselines_table.tex``
  * ``current works in progress/figures/auto/ablation_table.tex``
  * ``current works in progress/figures/auto/method_summary.tex``
  * ``current works in progress/figures/auto/accuracy_compare.pdf/.png``
  * ``current works in progress/figures/auto/final_accuracy_bar.pdf/.png``

The LaTeX files are designed to be ``\input{}``-ed from ``main.tex``; if no run
artifacts are available, the existing placeholders that ship with the repo
remain in place.
"""
from __future__ import annotations

import argparse
import csv
import json
import pathlib
from typing import Iterable

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


PAPER_DIR = pathlib.Path(__file__).resolve().parents[2] / "current works in progress"
AUTO_DIR = PAPER_DIR / "figures" / "auto"

BASELINE_IDS = ["fedavg", "fedavg_kyber", "fedprox", "qrqfl"]
ABLATION_IDS = ["qrqfl", "qrqfl_no_hmm", "qrqfl_no_dpp", "qrqfl_fixed_kyber"]


def _load(run_dir: pathlib.Path):
    summary = json.loads((run_dir / "summary.json").read_text())
    rows = list(csv.DictReader((run_dir / "accuracy_curves.csv").open()))
    return summary, rows


def _label_lookup(summary) -> dict[str, str]:
    return {m["id"]: m["label"] for m in summary["methods"]}


def _accuracy_for(rows, method_id: str):
    pairs = [(int(r["round"]), float(r["accuracy"])) for r in rows
             if r["method_id"] == method_id]
    pairs.sort()
    return pairs


def _final_acc(summary, method_id: str):
    for m in summary["methods"]:
        if m["id"] == method_id:
            return m["final_accuracy"]
    return None


def _baseline_table(summary, ids: Iterable[str]) -> str:
    cfg = summary["config"]
    lines = [
        "% Auto-generated by build_paper_tables.py - do not edit by hand.",
        "\\begin{tabular}{lcc}",
        "\\hline",
        "\\textbf{Method} & \\textbf{Final Acc.\\,(\\%)} & \\textbf{Rounds} \\\\",
        "\\hline",
    ]
    for mid in ids:
        for m in summary["methods"]:
            if m["id"] != mid:
                continue
            acc = m["final_accuracy"]
            acc_s = "--" if acc is None else f"{100 * acc:.2f}"
            lines.append(f"{m['label']} & {acc_s} & {m['rounds_run']} \\\\")
    lines += [
        "\\hline",
        "\\end{tabular}",
        f"% Run config: dataset={cfg['dataset']} N={cfg['n_clients']} "
        f"K={cfg['n_select']} rounds={cfg['n_rounds']} alpha={cfg['alpha']} "
        f"seed={cfg['seed']}",
    ]
    return "\n".join(lines) + "\n"


def _ablation_table(summary, ids) -> str:
    lines = [
        "% Auto-generated by build_paper_tables.py - do not edit by hand.",
        "\\begin{tabular}{lccccc}",
        "\\hline",
        "\\textbf{Variant} & \\textbf{HMM} & \\textbf{DPP} & "
        "\\textbf{PQ Adapt.} & \\textbf{Final Acc.\\,(\\%)} & \\textbf{Rounds} \\\\",
        "\\hline",
    ]
    for mid in ids:
        for m in summary["methods"]:
            if m["id"] != mid:
                continue
            qrq = m.get("qrq", {}) or {}
            hmm = "Y" if qrq.get("use_hmm", True) else "N"
            dpp = "Y" if qrq.get("use_dpp", True) else "N"
            pq_adapt = "N" if qrq.get("fixed_pq") or m.get("pq_force") else "Y"
            acc = m["final_accuracy"]
            acc_s = "--" if acc is None else f"{100 * acc:.2f}"
            lines.append(
                f"{m['label']} & {hmm} & {dpp} & {pq_adapt} & {acc_s} & {m['rounds_run']} \\\\"
            )
    lines += ["\\hline", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def _method_summary_paragraph(summary) -> str:
    cfg = summary["config"]
    return (
        "% Auto-generated by build_paper_tables.py - do not edit by hand.\n"
        f"All methods are run on {cfg['dataset'].upper()} with $N={cfg['n_clients']}$ "
        f"clients, $K={cfg['n_select']}$ selected per round, "
        f"$\\alpha{{=}}{cfg['alpha']}$ Dirichlet partitioning, batch size "
        f"{cfg['batch_size']}, and seed {cfg['seed']}, for "
        f"{cfg['n_rounds']} communication rounds. Each method shares the same "
        "data partition, model architecture, and centralised evaluation function.\n"
    )


def _accuracy_compare_plot(summary, rows, out_pdf, out_png, ids) -> None:
    plt.figure(figsize=(6.4, 3.8))
    for mid in ids:
        pairs = _accuracy_for(rows, mid)
        if not pairs:
            continue
        xs = [p[0] for p in pairs]
        ys = [100 * p[1] for p in pairs]
        plt.plot(xs, ys, marker="o", markersize=3,
                 label=_label_lookup(summary).get(mid, mid))
    plt.xlabel("Communication round")
    plt.ylabel("Centralised test accuracy (\u0025)")
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(out_pdf)
    plt.savefig(out_png, dpi=160)
    plt.close()


def _final_acc_bar(summary, out_pdf, out_png, ids) -> None:
    labels, vals = [], []
    for mid in ids:
        for m in summary["methods"]:
            if m["id"] != mid or m["final_accuracy"] is None:
                continue
            labels.append(m["label"])
            vals.append(100 * m["final_accuracy"])
    if not labels:
        return
    plt.figure(figsize=(6.4, 3.4))
    plt.bar(range(len(labels)), vals)
    plt.xticks(range(len(labels)), labels, rotation=20, ha="right", fontsize=8)
    plt.ylabel("Final accuracy (\u0025)")
    plt.grid(True, axis="y", alpha=0.3)
    plt.tight_layout()
    plt.savefig(out_pdf)
    plt.savefig(out_png, dpi=160)
    plt.close()


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("run_dir", help="Path to runs/<timestamp> created by run_baselines.py")
    args = ap.parse_args(argv)
    run_dir = pathlib.Path(args.run_dir)

    summary, rows = _load(run_dir)
    AUTO_DIR.mkdir(parents=True, exist_ok=True)

    (AUTO_DIR / "method_summary.tex").write_text(
        _method_summary_paragraph(summary), encoding="utf-8"
    )
    (AUTO_DIR / "baselines_table.tex").write_text(
        _baseline_table(summary, BASELINE_IDS), encoding="utf-8"
    )
    (AUTO_DIR / "ablation_table.tex").write_text(
        _ablation_table(summary, ABLATION_IDS), encoding="utf-8"
    )

    _accuracy_compare_plot(
        summary, rows,
        AUTO_DIR / "accuracy_compare.pdf",
        AUTO_DIR / "accuracy_compare.png",
        BASELINE_IDS,
    )
    _final_acc_bar(
        summary,
        AUTO_DIR / "final_accuracy_bar.pdf",
        AUTO_DIR / "final_accuracy_bar.png",
        BASELINE_IDS,
    )

    # Provenance file -- lets the paper say *which* run is being shown.
    (AUTO_DIR / "PROVENANCE.txt").write_text(
        json.dumps({
            "source_run": str(run_dir),
            "config": summary["config"],
            "methods": [m["id"] for m in summary["methods"]],
        }, indent=2),
        encoding="utf-8",
    )
    print(f"Wrote LaTeX/figures into {AUTO_DIR}")


if __name__ == "__main__":
    main()
